/// @description Variables 

target = obj_player;
walkspeed = 2; 
hp = 50;
jump_strength = 10;
grvty = 0.5;
max_overlap = 5;
normal_opacity = 1;
half_opacity = 0.5;
flash = 0;
verspeed = 0;
horspeed = 0;
spear_throw_cooldown = 0;
spear_throw_interval = 120; 
spear_in_hand = false;
my_spear = noone;
jump_cooldown = 20;
far_away_randomness = 10;